# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='header',
            field=models.ImageField(default='header/enen.jpg', upload_to='header/', verbose_name='用户头像'),
        ),
    ]
