# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='商品添加时间')),
                ('allTotal', models.FloatField(verbose_name='商品小计金额')),
                ('ready1', models.IntegerField(verbose_name='备用int字段')),
                ('ready2', models.CharField(max_length=255, verbose_name='备用str字段')),
                ('ready3', models.CharField(max_length=255, verbose_name='备用str字段2')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='购物车商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='购物车所属用户')),
            ],
        ),
    ]
