# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='ready1',
            field=models.IntegerField(blank=True, null=True, verbose_name='备用int字段'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='ready2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备用str字段'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='ready3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备用str字段2'),
        ),
    ]
